DB_HOST=localhost
DB_USER=root
DB_PASSWORD=
DB_NAME=aaisaheb_ecommerce_db


CLOUDINARY_CLOUD_NAME=dal6xgkdz
CLOUDINARY_API_KEY=963273291695542
CLOUDINARY_API_SECRET=JQku9uqRndjWWq6Sepet3Ieke6E

FAST2SMS_API_KEY=jgCKLnYPuerA6W35ozUS1OFEvXDwt7H4p098MkmlBGNZ2RQVhsR04KJ51QhOrVtaIDlob8AqETSmkU7P

JWT_SECRET=abfkuhujhdc9hncnk